id: playbook-PAN-OS_-_Lookup_Zone_Test
version: 6
name: playbook-PAN-OS_-_Lookup_Zone_Test
fromversion: 5.0.0
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c4a342ee-588f-4455-8f4e-3a9e0c1dbbd2
    type: start
    task:
      id: c4a342ee-588f-4455-8f4e-3a9e0c1dbbd2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 4f69d4e4-720b-4918-8ed4-d17a9b3f96c2
    type: regular
    task:
      id: 4f69d4e4-720b-4918-8ed4-d17a9b3f96c2
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: c10f2ec8-c4d6-47df-8758-e5af5b86efa7
    type: regular
    task:
      id: c10f2ec8-c4d6-47df-8758-e5af5b86efa7
      version: -1
      name: panorama-lookup-route
      script: '|||panorama-lookup-route'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      dest_ip:
        simple: ${inputs.dest_ip}
      virtual_router:
        simple: ${inputs.virtual_router}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 7958fd6f-9447-476f-8766-77e9772d87f4
    type: condition
    task:
      id: 7958fd6f-9447-476f-8766-77e9772d87f4
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Panorama.RouteLookup.interface
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: c2651784-810c-408c-8a74-bfb18e4187ec
    type: regular
    task:
      id: c2651784-810c-408c-8a74-bfb18e4187ec
      version: -1
      name: panorama-lookup-zone
      script: '|||panorama-lookup-zone'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      dest_ip:
        simple: ${inputs.dest_ip}
      virtual_router:
        simple: ${inputs.virtual_router}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 61d06cac-603b-43d9-8f87-ebe3f1117ba2
    type: condition
    task:
      id: 61d06cac-603b-43d9-8f87-ebe3f1117ba2
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Panorama.ZoneLookup.zone
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Panorama.ZoneLookup.interface
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Panorama.ZoneLookup.dest_ip
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: e06d3c49-a460-454c-80b4-18ef89ecad83
    type: title
    task:
      id: e06d3c49-a460-454c-80b4-18ef89ecad83
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1215,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: dest_ip
  value:
    simple: 8.8.8.8
  required: false
  description: ""
  playbookInputQuery: null
- key: virtual_router
  value:
    simple: default
  required: false
  description: ""
  playbookInputQuery: null
outputs: []
