commonfields:
  id: XDR_test_helper
  version: -1
name: XDR_test_helper
script: |+
  args = demisto.args()
  indicator =  args['indicator']
  data = demisto.searchIndicators(value=indicator)['iocs'][0]['moduleToFeedMap']
  for indicator_reputation in data.values():
      if indicator_reputation.get('sourceBrand') == 'Cortex XDR - IOC':
          return_outputs('', outputs={indicator.replace('.', '_'): indicator_reputation['fields']['xdr']})
          break

type: python
tags: []
enabled: true
args:
- name: indicator
  required: true
  description: ''
scripttarget: 0
subtype: python3
runonce: false
dockerimage: demisto/python3:3.8.3.9324
runas: DBotWeakRole
comment: ''
fromversion: '5.5.0'
